# Global
## Set the domain to create nginx for argocd and other service ingress
domain: 
## Set local if you wish to use "local-path" in your cluster 
storage:
  local:
    enable: true
# Application specific
githubactionsrunner:
  enable: false
  token: ""
cats:
  storageClass: "local-path"
observability:
  storageClass: "local-path"
  pdkey:
  storageSize: 10Gi
  retention: 5d
trivy:
  enable: true
komodor:
  enable: false
  key:
  clustername:
logging:
  enable: true
